blank_issues_enabled: false
contact_links:
  - name: Kite Community Support
    url: https://github.com/kite-opensource/kite/discussions
    about: Ask questions or discuss features here
  - name: Documentation
    url: https://kite-opensource.github.io/kite-docs/
    about: Check the official Kite documentation